Automatic and integrated compilation of farsight utility
git-svn-id: svn://svn.code.sf.net/p/amsn/code/trunk@9727 f248a3e1-9e13-0410-b2cf-a4429de6d898

diff --git a/amsn/configure b/amsn/configure
--- a/amsn/configure
+++ b/amsn/configure
@@ -695,6 +695,13 @@ GREP
 EGREP
 LIBPTHREAD
 USE_MMX
+HAVE_PKGCONFIG
+PKG_CONFIG
+GST_CFLAGS
+GST_LIBS
+FARSIGHT2_CFLAGS
+FARSIGHT2_LIBS
+HAVE_FARSIGHT
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -710,7 +717,12 @@ CXX
 CXXFLAGS
 CCC
 XMKMF
-CPP'
+CPP
+PKG_CONFIG
+GST_CFLAGS
+GST_LIBS
+FARSIGHT2_CFLAGS
+FARSIGHT2_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1306,6 +1318,13 @@ Some influential environment variables:
   CXXFLAGS    C++ compiler flags
   XMKMF       Path to xmkmf, Makefile generator for X Window System
   CPP         C preprocessor
+  PKG_CONFIG  path to pkg-config utility
+  GST_CFLAGS  C compiler flags for GST, overriding pkg-config
+  GST_LIBS    linker flags for GST, overriding pkg-config
+  FARSIGHT2_CFLAGS
+              C compiler flags for FARSIGHT2, overriding pkg-config
+  FARSIGHT2_LIBS
+              linker flags for FARSIGHT2, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -6511,6 +6530,343 @@ fi
 { echo "$as_me:$LINENO: result: $USE_MMX" >&5
 echo "${ECHO_T}$USE_MMX" >&6; }
 
+HAVE_FARSIGHT=no
+GST_REQUIRED=0.10.17
+GST_MAJORMINOR=0.10
+FARSIGHT_REQUIRED=0.0.2
+
+# Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_HAVE_PKGCONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$HAVE_PKGCONFIG"; then
+  ac_cv_prog_HAVE_PKGCONFIG="$HAVE_PKGCONFIG" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_HAVE_PKGCONFIG="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_HAVE_PKGCONFIG" && ac_cv_prog_HAVE_PKGCONFIG="no"
+fi
+fi
+HAVE_PKGCONFIG=$ac_cv_prog_HAVE_PKGCONFIG
+if test -n "$HAVE_PKGCONFIG"; then
+  { echo "$as_me:$LINENO: result: $HAVE_PKGCONFIG" >&5
+echo "${ECHO_T}$HAVE_PKGCONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
+
+if test "x$HAVE_PKGCONFIG" = "xyes"; then
+
+
+if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
+	if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
+set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+fi
+if test -z "$ac_cv_path_PKG_CONFIG"; then
+  ac_pt_PKG_CONFIG=$PKG_CONFIG
+  # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_ac_pt_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $ac_pt_PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_PKG_CONFIG="$ac_pt_PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_ac_pt_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ac_pt_PKG_CONFIG=$ac_cv_path_ac_pt_PKG_CONFIG
+if test -n "$ac_pt_PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $ac_pt_PKG_CONFIG" >&5
+echo "${ECHO_T}$ac_pt_PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+  if test "x$ac_pt_PKG_CONFIG" = x; then
+    PKG_CONFIG=""
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ echo "$as_me:$LINENO: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&5
+echo "$as_me: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&2;}
+ac_tool_warned=yes ;;
+esac
+    PKG_CONFIG=$ac_pt_PKG_CONFIG
+  fi
+else
+  PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
+fi
+
+fi
+if test -n "$PKG_CONFIG"; then
+	_pkg_min_version=0.9.0
+	{ echo "$as_me:$LINENO: checking pkg-config is at least version $_pkg_min_version" >&5
+echo $ECHO_N "checking pkg-config is at least version $_pkg_min_version... $ECHO_C" >&6; }
+	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		PKG_CONFIG=""
+	fi
+
+fi
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for GST" >&5
+echo $ECHO_N "checking for GST... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$GST_CFLAGS"; then
+        pkg_cv_GST_CFLAGS="$GST_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\\
+    gstreamer-\$GST_MAJORMINOR >= \$GST_REQUIRED\"") >&5
+  ($PKG_CONFIG --exists --print-errors "\
+    gstreamer-$GST_MAJORMINOR >= $GST_REQUIRED") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GST_CFLAGS=`$PKG_CONFIG --cflags "\
+    gstreamer-$GST_MAJORMINOR >= $GST_REQUIRED" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$GST_LIBS"; then
+        pkg_cv_GST_LIBS="$GST_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\\
+    gstreamer-\$GST_MAJORMINOR >= \$GST_REQUIRED\"") >&5
+  ($PKG_CONFIG --exists --print-errors "\
+    gstreamer-$GST_MAJORMINOR >= $GST_REQUIRED") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GST_LIBS=`$PKG_CONFIG --libs "\
+    gstreamer-$GST_MAJORMINOR >= $GST_REQUIRED" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GST_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "\
+    gstreamer-$GST_MAJORMINOR >= $GST_REQUIRED"`
+        else
+	        GST_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "\
+    gstreamer-$GST_MAJORMINOR >= $GST_REQUIRED"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GST_PKG_ERRORS" >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+                HAVE_GST=no
+elif test $pkg_failed = untried; then
+	HAVE_GST=no
+else
+	GST_CFLAGS=$pkg_cv_GST_CFLAGS
+	GST_LIBS=$pkg_cv_GST_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	HAVE_GST=yes
+fi
+
+    if test "x$HAVE_GST" = "xyes"; then
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for FARSIGHT2" >&5
+echo $ECHO_N "checking for FARSIGHT2... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$FARSIGHT2_CFLAGS"; then
+        pkg_cv_FARSIGHT2_CFLAGS="$FARSIGHT2_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\\
+           farsight2-\$GST_MAJORMINOR >= \$FARSIGHT_REQUIRED\"") >&5
+  ($PKG_CONFIG --exists --print-errors "\
+           farsight2-$GST_MAJORMINOR >= $FARSIGHT_REQUIRED") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_FARSIGHT2_CFLAGS=`$PKG_CONFIG --cflags "\
+           farsight2-$GST_MAJORMINOR >= $FARSIGHT_REQUIRED" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$FARSIGHT2_LIBS"; then
+        pkg_cv_FARSIGHT2_LIBS="$FARSIGHT2_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\\
+           farsight2-\$GST_MAJORMINOR >= \$FARSIGHT_REQUIRED\"") >&5
+  ($PKG_CONFIG --exists --print-errors "\
+           farsight2-$GST_MAJORMINOR >= $FARSIGHT_REQUIRED") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_FARSIGHT2_LIBS=`$PKG_CONFIG --libs "\
+           farsight2-$GST_MAJORMINOR >= $FARSIGHT_REQUIRED" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        FARSIGHT2_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "\
+           farsight2-$GST_MAJORMINOR >= $FARSIGHT_REQUIRED"`
+        else
+	        FARSIGHT2_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "\
+           farsight2-$GST_MAJORMINOR >= $FARSIGHT_REQUIRED"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$FARSIGHT2_PKG_ERRORS" >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+                HAVE_FARSIGHT=no
+elif test $pkg_failed = untried; then
+	HAVE_FARSIGHT=no
+else
+	FARSIGHT2_CFLAGS=$pkg_cv_FARSIGHT2_CFLAGS
+	FARSIGHT2_LIBS=$pkg_cv_FARSIGHT2_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	HAVE_FARSIGHT=yes
+fi
+  fi
+
+fi
+
+
+
+
+
+
+
+
 
 ac_config_files="$ac_config_files Makefile"
 
@@ -7211,11 +7567,18 @@ GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
 LIBPTHREAD!$LIBPTHREAD$ac_delim
 USE_MMX!$USE_MMX$ac_delim
+HAVE_PKGCONFIG!$HAVE_PKGCONFIG$ac_delim
+PKG_CONFIG!$PKG_CONFIG$ac_delim
+GST_CFLAGS!$GST_CFLAGS$ac_delim
+GST_LIBS!$GST_LIBS$ac_delim
+FARSIGHT2_CFLAGS!$FARSIGHT2_CFLAGS$ac_delim
+FARSIGHT2_LIBS!$FARSIGHT2_LIBS$ac_delim
+HAVE_FARSIGHT!$HAVE_FARSIGHT$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 84; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 91; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -7650,8 +8013,14 @@ compile time options summary
     TK 		 : $TK_VERSION
     DEBUG        : $DEBUG
     STATIC       : $STATIC
+    FARSIGHT     : $HAVE_FARSIGHT
 
 EOF
 
+if test x"$HAVE_FARSIGHT" = "xno"; then
+   echo "*** You do not seem to have gstreamer and farsight2 installed."
+   echo "*** You will not be able to build the required component for audio conversations."
+   echo "*** Read this for more information : http://amsn-project.net/wiki/Farsight"
+fi
 
 exit 0
