Add ::Farsight::Probe to probe devices and give the list of input devices available
git-svn-id: svn://svn.code.sf.net/p/amsn/code/trunk@10692 f248a3e1-9e13-0410-b2cf-a4429de6d898

diff --git a/amsn/configure b/amsn/configure
--- a/amsn/configure
+++ b/amsn/configure
@@ -702,6 +702,8 @@ GLIB_CFLAGS
 GLIB_LIBS
 GST_CFLAGS
 GST_LIBS
+GST_INTERFACES_CFLAGS
+GST_INTERFACES_LIBS
 FARSIGHT2_CFLAGS
 FARSIGHT2_LIBS
 LIBV4L_CFLAGS
@@ -728,6 +730,8 @@ GLIB_CFLAGS
 GLIB_LIBS
 GST_CFLAGS
 GST_LIBS
+GST_INTERFACES_CFLAGS
+GST_INTERFACES_LIBS
 FARSIGHT2_CFLAGS
 FARSIGHT2_LIBS
 LIBV4L_CFLAGS
@@ -1332,6 +1336,10 @@ Some influential environment variables:
   GLIB_LIBS   linker flags for GLIB, overriding pkg-config
   GST_CFLAGS  C compiler flags for GST, overriding pkg-config
   GST_LIBS    linker flags for GST, overriding pkg-config
+  GST_INTERFACES_CFLAGS
+              C compiler flags for GST_INTERFACES, overriding pkg-config
+  GST_INTERFACES_LIBS
+              linker flags for GST_INTERFACES, overriding pkg-config
   FARSIGHT2_CFLAGS
               C compiler flags for FARSIGHT2, overriding pkg-config
   FARSIGHT2_LIBS
@@ -6873,6 +6881,86 @@ echo "${ECHO_T}yes" >&6; }
 	HAVE_GST=yes
 fi
 
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for GST_INTERFACES" >&5
+echo $ECHO_N "checking for GST_INTERFACES... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$GST_INTERFACES_CFLAGS"; then
+        pkg_cv_GST_INTERFACES_CFLAGS="$GST_INTERFACES_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\\
+      gstreamer-interfaces-\$GST_MAJORMINOR >= \$GST_REQUIRED\"") >&5
+  ($PKG_CONFIG --exists --print-errors "\
+      gstreamer-interfaces-$GST_MAJORMINOR >= $GST_REQUIRED") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GST_INTERFACES_CFLAGS=`$PKG_CONFIG --cflags "\
+      gstreamer-interfaces-$GST_MAJORMINOR >= $GST_REQUIRED" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$GST_INTERFACES_LIBS"; then
+        pkg_cv_GST_INTERFACES_LIBS="$GST_INTERFACES_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\\
+      gstreamer-interfaces-\$GST_MAJORMINOR >= \$GST_REQUIRED\"") >&5
+  ($PKG_CONFIG --exists --print-errors "\
+      gstreamer-interfaces-$GST_MAJORMINOR >= $GST_REQUIRED") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GST_INTERFACES_LIBS=`$PKG_CONFIG --libs "\
+      gstreamer-interfaces-$GST_MAJORMINOR >= $GST_REQUIRED" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GST_INTERFACES_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "\
+      gstreamer-interfaces-$GST_MAJORMINOR >= $GST_REQUIRED"`
+        else
+	        GST_INTERFACES_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "\
+      gstreamer-interfaces-$GST_MAJORMINOR >= $GST_REQUIRED"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GST_INTERFACES_PKG_ERRORS" >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+                HAVE_GST_INTERFACES=no
+elif test $pkg_failed = untried; then
+	HAVE_GST_INTERFACES=no
+else
+	GST_INTERFACES_CFLAGS=$pkg_cv_GST_INTERFACES_CFLAGS
+	GST_INTERFACES_LIBS=$pkg_cv_GST_INTERFACES_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	HAVE_GST_INTERFACES=yes
+fi
+
         if test "x$HAVE_GST" = "xyes"; then
 
 pkg_failed=no
@@ -7036,6 +7124,8 @@ echo "${ECHO_T}yes" >&6; }
 	HAVE_LIBV4L=yes
 fi
 fi
+
+
 
 
 
@@ -7751,16 +7841,17 @@ GLIB_CFLAGS!$GLIB_CFLAGS$ac_delim
 GLIB_LIBS!$GLIB_LIBS$ac_delim
 GST_CFLAGS!$GST_CFLAGS$ac_delim
 GST_LIBS!$GST_LIBS$ac_delim
+GST_INTERFACES_CFLAGS!$GST_INTERFACES_CFLAGS$ac_delim
+GST_INTERFACES_LIBS!$GST_INTERFACES_LIBS$ac_delim
 FARSIGHT2_CFLAGS!$FARSIGHT2_CFLAGS$ac_delim
 FARSIGHT2_LIBS!$FARSIGHT2_LIBS$ac_delim
 LIBV4L_CFLAGS!$LIBV4L_CFLAGS$ac_delim
 LIBV4L_LIBS!$LIBV4L_LIBS$ac_delim
 HAVE_FARSIGHT!$HAVE_FARSIGHT$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
-LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 96; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -7792,6 +7883,50 @@ N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
 ' >>$CONFIG_STATUS <conf$$subs.sed
 rm -f conf$$subs.sed
 cat >>$CONFIG_STATUS <<_ACEOF
+CEOF$ac_eof
+_ACEOF
+
+
+ac_delim='%!_!# '
+for ac_last_try in false false false false false :; do
+  cat >conf$$subs.sed <<_ACEOF
+LTLIBOBJS!$LTLIBOBJS$ac_delim
+_ACEOF
+
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 1; then
+    break
+  elif $ac_last_try; then
+    { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
+echo "$as_me: error: could not make $CONFIG_STATUS" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    ac_delim="$ac_delim!$ac_delim _$ac_delim!! "
+  fi
+done
+
+ac_eof=`sed -n '/^CEOF[0-9]*$/s/CEOF/0/p' conf$$subs.sed`
+if test -n "$ac_eof"; then
+  ac_eof=`echo "$ac_eof" | sort -nru | sed 1q`
+  ac_eof=`expr $ac_eof + 1`
+fi
+
+cat >>$CONFIG_STATUS <<_ACEOF
+cat >"\$tmp/subs-2.sed" <<\CEOF$ac_eof
+/@[a-zA-Z_][a-zA-Z_0-9]*@/!b end
+_ACEOF
+sed '
+s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g
+s/^/s,@/; s/!/@,|#_!!_#|/
+:n
+t n
+s/'"$ac_delim"'$/,g/; t
+s/$/\\/; p
+N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
+' >>$CONFIG_STATUS <conf$$subs.sed
+rm -f conf$$subs.sed
+cat >>$CONFIG_STATUS <<_ACEOF
+:end
+s/|#_!!_#|//g
 CEOF$ac_eof
 _ACEOF
 
@@ -8034,7 +8169,7 @@ s&@builddir@&$ac_builddir&;t t
 s&@abs_builddir@&$ac_abs_builddir&;t t
 s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 $ac_datarootdir_hack
-" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed 's/|#_!!_#|//g' >$tmp/out
+" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" >$tmp/out
 
 test -z "$ac_datarootdir_hack$ac_datarootdir_seen" &&
   { ac_out=`sed -n '/\${datarootdir}/p' "$tmp/out"`; test -n "$ac_out"; } &&
